version: "3.1"

services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASS}"
      MONGO_INITDB_DATABASE: "${DB_DEFAULT_DATABASE}"
    ports:
      - "${DB_PORT}:${DB_PORT}"

  inspector:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${DB_USER}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${DB_PASS}"
      ME_CONFIG_MONGODB_URL: "mongodb://${DB_USER}:${DB_PASS}@db:${DB_PORT}/"
    depends_on:
      - db
